apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: covid-app
  name: covid-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: covid-app
  template:
    metadata:
      labels:
        app: covid-app
    spec:
      containers:
      - name: my-covid-app
        image: 353258999787.dkr.ecr.us-east-1.amazonaws.com/spring-boot-microservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: covid-app
    k8s-app: covid-app
  name: covid-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: covid-app
